# Backend Dockerfile
FROM openjdk:17-jdk-slim
VOLUME /tmp

# 빌드 인수를 활용할 수 있는 부분 예시
ENV SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
ENV SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
ENV AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
ENV AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

COPY build/libs/*.jar app.jar
ENTRYPOINT ["java", \
"-DSPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}", \
"-DSPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}", \
"-DAWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}", \
"-DAWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}", \
"-jar", \
"/app.jar"]
