version: '3.8'

services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3030:80"
    networks:
      - app-network

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "4040:4040"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
