version: '3.8'

services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3030:80"
    networks:
      - app-network

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "4040:4040"
    networks:
      - app-network
    volumes:
      - ./backend/nginx.conf:/etc/nginx/nginx.conf

  nginx:
    image: nginx:1.27.0-alpine
    ports:
      - "80:80"
    volumes:
      - ./backend/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
