# Backend Dockerfile
FROM openjdk:17-jdk-slim
VOLUME /tmp

# 빌드 인수 선언
ARG SPRING_MAIL_USERNAME
ARG SPRING_MAIL_PASSWORD
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY

# 빌드 인수를 활용할 수 있는 부분 예시
ENV SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
ENV SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
ENV AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
ENV AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

COPY build/libs/*.jar app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
