services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_ROOT_PASSWORD: '1234'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - D:\multicampus\Project\ganwonActivity:/var/lib/mysql
    ports:
      - "3307:3306"
  spring-app:
    build:
      dockerfile: Dockerfile
    ports:
      - "4040:4040"
    depends_on:
      - mysql