name: main workflow
on: push
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment variables
        env:
          SPRING_MAIL_USERNAME: ${{ secrets.SPRING_MAIL_USERNAME }}
          SPRING_MAIL_PASSWORD: ${{ secrets.SPRING_MAIL_PASSWORD }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: |
          echo "Setting environment variables for Spring Boot application."
          echo $SPRING_MAIL_USERNAME
          echo $SPRING_MAIL_PASSWORD
          echo $AWS_ACCESS_KEY
          echo $AWS_SECRET_KEY
